package com.test.hilttestfragment.screens

import androidx.test.espresso.Espresso.onView
import androidx.test.espresso.assertion.ViewAssertions.matches
import androidx.test.espresso.matcher.ViewMatchers
import androidx.test.espresso.matcher.ViewMatchers.withId
import com.test.hilttestfragment.R
import com.test.hilttestfragment.utils.launchFragmentInHiltContainer
import dagger.hilt.android.testing.HiltAndroidRule
import dagger.hilt.android.testing.HiltAndroidTest
import org.junit.Rule
import org.junit.Test

@HiltAndroidTest
class HiltFragmentTest {

    @get:Rule
    var hiltRule = HiltAndroidRule(this)

    @Test
    fun testFragment() {
        launchFragmentInHiltContainer<HiltFragment> {
            onView(withId(R.id.fragment_text)).check(matches(ViewMatchers.withText("Api call\nDummy response generated by NetworkService through Test Hilt")))
        }
    }
}