package com.test.hilttestfragment.di

import com.test.hilttestfragment.network.NetworkService
import dagger.Module
import dagger.Provides
import dagger.hilt.components.SingletonComponent
import dagger.hilt.testing.TestInstallIn
import javax.inject.Singleton

@Module
@TestInstallIn(
    components = [SingletonComponent::class],
    replaces = [NetworkModule::class]
)
class NetworkFakeModule {
    @Singleton
    @Provides
    fun provideNetworkService(): NetworkService {
        return NetworkService().apply {
            fakeResponse = "$fakeResponse generated by NetworkService through Test Hilt"
        }
    }
}